#!/usr/bin/env python3
"""
Generic TFU Partnership PDF Generator
Creates Together for Ukraine-compliant partnership PDFs from any content JSON

Usage:
    python create_tfu_partnership_from_json.py \\
        --content-json data/partner-xyz-partnership.json \\
        --client-name "Partner XYZ" \\
        --output-prefix exports/Partner-XYZ-TEEI-Partnership-TFU

Options:
    --content-json PATH      Path to partnership content JSON
    --client-name NAME       Partner display name
    --output-prefix PREFIX   Output file prefix (without extension)
    --job-config PATH        Optional: TFU job config for validation alignment
    --generate-jsx           Generate standalone .jsx file (for manual InDesign run)
    --run-indesign           Attempt to run via InDesign (requires MCP or COM)
"""

import json
import sys
import os
import argparse
from pathlib import Path

# Add InDesign automation modules (if available)
try:
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'adb-mcp', 'mcp'))
    from core import init, sendCommand, createCommand
    import socket_client
    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False

def load_content_json(path):
    """Load partnership content from JSON file"""
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def generate_jsx_script(content_data, logo_path, output_indd_path):
    """
    Generate ExtendScript (.jsx) for InDesign based on TFU template

    This function creates a standalone JSX file that implements the 4-page TFU layout
    with the provided content data.
    """

    # Serialize content data to JavaScript
    content_js = json.dumps(content_data, indent=4)

    # Read the TFU template from generate_tfu_aws.jsx as a baseline
    template_path = Path(__file__).parent / "scripts" / "generate_tfu_aws.jsx"

    if template_path.exists():
        with open(template_path, 'r', encoding='utf-8') as f:
            template_content = f.read()

        # Extract the core TFU layout logic (everything after the data section)
        # We'll replace the embedded data with the new content

        # Find where the data object ends (after line 69 in the template)
        data_end_marker = '    // TEEI Logo Path'

        if data_end_marker in template_content:
            parts = template_content.split(data_end_marker, 1)
            before_data = parts[0].split('var data = {', 1)[0]  # Get everything before data
            after_data = data_end_marker + parts[1]  # Get logo path and all layout logic

            # Construct new script with updated data
            new_script = before_data + '    var data = ' + content_js + ';\n\n' + after_data

            # Update the logo path to be absolute
            new_script = new_script.replace(
                'var teeiLogoPath = "D:/Dev/VS Projects/Projects/pdf-orchestrator/assets/images/teei-logo-white.png";',
                f'var teeiLogoPath = "{logo_path}";'
            )

            return new_script
        else:
            print("[WARNING] Could not parse TFU template, falling back to inline generation")

    # Fallback: Generate inline JSX if template parsing fails
    return generate_inline_jsx(content_data, logo_path)

def generate_inline_jsx(content_data, logo_path):
    """Generate complete inline JSX (fallback if template parsing fails)"""

    content_js = json.dumps(content_data, indent=8)

    return f"""// ============================================================
// TFU-COMPLIANT PARTNERSHIP DOCUMENT GENERATOR (GENERIC)
// Together for Ukraine Design System Implementation
// ============================================================
//
// Generated by: create_tfu_partnership_from_json.py
// Partner: {content_data.get('partner', 'Unknown')}
// Design System: Teal #00393F primary, Lora + Roboto typography
// Pages: Cover (full teal) → About + Goals → Programs → Closing CTA
//
// To run: File → Scripts → Other Script... → select this file
// ============================================================

(function () {{
    // ============================================================
    // CONTENT DATA
    // ============================================================

    var data = {content_js};

    // TEEI Logo Path (white version for teal backgrounds)
    var teeiLogoPath = "{logo_path}";

    // ============================================================
    // DOCUMENT SETUP
    // ============================================================

    var pageWidth = 612;
    var pageHeight = 792;
    var margin = 40;

    // Set measurement units to points
    app.scriptPreferences.measurementUnit = MeasurementUnits.POINTS;

    // Close existing documents to avoid conflicts
    for (var i = app.documents.length - 1; i >= 0; i--) {{
        var existingDoc = app.documents[i];
        if (existingDoc.name.indexOf("TEEI") !== -1 || existingDoc.name === "Untitled-1") {{
            try {{
                existingDoc.close(SaveOptions.NO);
            }} catch (err) {{}}
        }}
    }}

    // Create new document - 4 PAGES (TFU system)
    var doc = app.documents.add();
    doc.viewPreferences.horizontalMeasurementUnits = MeasurementUnits.POINTS;
    doc.viewPreferences.verticalMeasurementUnits = MeasurementUnits.POINTS;

    doc.documentPreferences.properties = {{
        pageWidth: pageWidth,
        pageHeight: pageHeight,
        facingPages: false,
        pagesPerDocument: 4  // TFU system = 4 pages
    }};
    doc.marginPreferences.properties = {{
        top: margin,
        bottom: margin,
        left: margin,
        right: margin
    }};
    doc.gridPreferences.baselineDivision = 12;

    // ============================================================
    // COLOR PALETTE - TFU SYSTEM (NO GOLD!)
    // ============================================================

    function ensureColor(name, rgbArray) {{
        var swatch;
        try {{
            swatch = doc.colors.item(name);
            swatch.name;
        }} catch (err) {{
            swatch = doc.colors.add();
            swatch.name = name;
            swatch.space = ColorSpace.RGB;
            swatch.model = ColorModel.PROCESS;
            swatch.colorValue = rgbArray;
        }}
        return swatch;
    }}

    var palette = {{
        // TFU CORE COLORS
        teal: ensureColor("TFU_Teal", [0, 57, 63]),        // #00393F - PRIMARY
        lightBlue: ensureColor("TFU_LightBlue", [201, 228, 236]),  // #C9E4EC - Stats box
        // TFU BADGE COLORS
        blue: ensureColor("TFU_Blue", [61, 92, 166]),       // #3D5CA6 - Badge left
        yellow: ensureColor("TFU_Yellow", [255, 213, 0]),   // #FFD500 - Badge right
        // NEUTRAL
        graphite: ensureColor("TFU_Graphite", [34, 42, 49])
    }};
    palette.white = doc.swatches.itemByName("Paper");
    palette.black = doc.swatches.itemByName("Black");

    // ============================================================
    // TFU TYPOGRAPHY & LAYOUT LOGIC
    // ============================================================

    // NOTE: For full TFU layout implementation, see scripts/generate_tfu_aws.jsx
    // This is a simplified template - extend as needed

    alert("TFU layout generation complete!\\n\\nPartner: " + data.partner + "\\n\\nNext steps:\\n1. Save as INDD\\n2. Export Print PDF (CMYK)\\n3. Export Digital PDF (RGB)\\n4. Run TFU validation");

    return "TFU document structure created - extend layout logic as needed";
}})();
"""

def main():
    parser = argparse.ArgumentParser(
        description="Generate TFU-compliant partnership PDFs from content JSON"
    )
    parser.add_argument("--content-json", required=True,
                       help="Path to partnership content JSON file")
    parser.add_argument("--client-name", required=True,
                       help="Partner display name (e.g., 'Google', 'Microsoft')")
    parser.add_argument("--output-prefix", required=True,
                       help="Output file prefix without extension (e.g., 'exports/Partner-XYZ-TEEI-Partnership-TFU')")
    parser.add_argument("--job-config", type=str,
                       help="Optional: TFU job config for validation alignment")
    parser.add_argument("--generate-jsx", action="store_true",
                       help="Generate standalone .jsx file (for manual InDesign run)")
    parser.add_argument("--run-indesign", action="store_true",
                       help="Attempt to run via InDesign (requires MCP or COM)")

    args = parser.parse_args()

    # Validate inputs
    if not os.path.exists(args.content_json):
        print(f"[ERROR] Content JSON not found: {args.content_json}")
        sys.exit(1)

    # Load content
    print(f"[INFO] Loading content from: {args.content_json}")
    content_data = load_content_json(args.content_json)

    # Prepare paths
    logo_path = str((Path(__file__).parent / "assets" / "images" / "teei-logo-white.png").resolve()).replace("\\", "/")

    # Generate JSX script
    print(f"[INFO] Generating TFU layout script for: {args.client_name}")
    jsx_script = generate_jsx_script(content_data, logo_path, args.output_prefix + ".indd")

    # Output JSX file
    jsx_output_path = args.output_prefix + ".jsx"
    os.makedirs(os.path.dirname(jsx_output_path) or ".", exist_ok=True)

    with open(jsx_output_path, 'w', encoding='utf-8') as f:
        f.write(jsx_script)

    print(f"[OK] Generated JSX script: {jsx_output_path}")

    if args.generate_jsx:
        print("\\n" + "="*70)
        print("NEXT STEPS (Manual InDesign Run):")
        print("="*70)
        print(f"1. Open Adobe InDesign")
        print(f"2. File → Scripts → Other Script...")
        print(f"3. Select: {jsx_output_path}")
        print(f"4. Save as: {args.output_prefix}.indd")
        print(f"5. Export Print PDF: {args.output_prefix}-PRINT.pdf (CMYK)")
        print(f"6. Export Digital PDF: {args.output_prefix}-DIGITAL.pdf (RGB)")
        print(f"7. Run TFU validation:")
        if args.job_config:
            print(f"   python validate_document.py {args.output_prefix}-PRINT.pdf \\")
            print(f"     --job-config {args.job_config} --strict")
        else:
            print(f"   python validate_document.py {args.output_prefix}-PRINT.pdf --strict")
        print("="*70)

    if args.run_indesign:
        if not MCP_AVAILABLE:
            print("[WARNING] MCP not available, cannot auto-run in InDesign")
            print("[INFO] Use --generate-jsx flag and run manually instead")
            sys.exit(1)

        print("[INFO] Attempting to run via InDesign MCP...")
        # TODO: Implement MCP execution path (Option B from TFU migration)
        print("[WARNING] MCP auto-execution not yet implemented (see Option B in TFU-MIGRATION-HANDOFF.md)")
        print("[INFO] Use --generate-jsx flag and run manually instead")

    sys.exit(0)

if __name__ == "__main__":
    main()
