#!/usr/bin/env python3
"""
Generate Python MCP tool wrappers for all 61 InDesign UXP commands.
Parses index.js and creates @mcp.tool() decorated functions.
"""

import re
import json

# Read the UXP commands JavaScript file
with open(r"T:\Projects\pdf-orchestrator\adb-mcp\uxp\id\commands\index.js", "r", encoding="utf-8") as f:
    js_content = f.read()

# Find all command function definitions
command_pattern = r"const (\w+) = async \(command\) => \{"
commands = re.findall(command_pattern, js_content)

print(f"Found {len(commands)} commands")
print(f"Commands: {', '.join(commands[:10])}...")

# Generate Python MCP wrapper template
def generate_wrapper(command_name):
    """Generate a Python MCP tool wrapper for a command"""

    # Convert camelCase to snake_case for Python
    snake_name = re.sub(r'(?<!^)(?=[A-Z])', '_', command_name).lower()

    return f'''
@mcp.tool()
def {snake_name}(
    **kwargs
):
    """
    {command_name} - Executes the {command_name} command in InDesign.

    This is an auto-generated wrapper. Pass all required parameters as keyword arguments.
    See the InDesign UXP plugin documentation for available parameters.

    Args:
        **kwargs: All command-specific parameters

    Returns:
        dict: Result of the command execution from the InDesign UXP plugin
    """
    command = createCommand("{command_name}", kwargs)
    return sendCommand(command)
'''

# Generate all wrappers
output = []
output.append("# ============================================================================")
output.append("# AUTO-GENERATED MCP TOOL WRAPPERS FOR ALL 61 INDESIGN COMMANDS")
output.append("# Generated by: scripts/generate-mcp-wrappers.py")
output.append("# ============================================================================")
output.append("")

# Skip these commands (already manually defined in id-mcp.py or internal only)
skip_commands = [
    "parseAndRouteCommand",
    "checkRequiresActiveDocument",
    "getActiveDocumentSettings",
    "createDocument",  # Already manually defined with better docs
    "createTextFrame"  # Already manually defined as create_text_frame
]

for cmd in commands:
    if cmd not in skip_commands:
        output.append(generate_wrapper(cmd))

# Write to file
output_file = r"T:\Projects\pdf-orchestrator\adb-mcp\mcp\generated_tools.py"
with open(output_file, "w", encoding="utf-8") as f:
    f.write("\n".join(output))

print(f"\n[OK] Generated {len(commands)} MCP tool wrappers")
print(f"[FILE] Output: {output_file}")
print(f"\n[NEXT] Next steps:")
print(f"1. Review generated_tools.py")
print(f"2. Import in id-mcp.py: from generated_tools import *")
print(f"3. Restart Claude Code to load new tools")

# Also print the import statement to add to id-mcp.py
print(f"\n[NOTE] Add this to id-mcp.py after line 49 (after init()):")
print(f"   exec(open(r'T:\\Projects\\pdf-orchestrator\\adb-mcp\\mcp\\generated_tools.py').read())")
